/**
 * Source detection (FR-3): what produced this upload, with confidence and the
 * evidence shown in the detection badge popover (DESIGN.md §5.4).
 */

export type SourceType = 'lovable' | 'bolt' | 'vite-spa' | 'next-export' | 'ai-html' | 'html-template' | 'html' | 'source-zip' | 'unknown';

export type SourceInfo = {
	type: SourceType;
	label: string;
	confidence: number;
	evidence: string[];
	/** Needs a JS runtime to render (an SPA shell). */
	spa: boolean;
};

export type DetectInput = {
	/** Relative file paths inside the upload (a single file upload is ["index.html"]). */
	files: string[];
	/** Contents of the entry HTML file. */
	html: string;
};

export function detectSource( { files, html }: DetectInput ): SourceInfo {
	const evidence: string[] = [];
	const lower = files.map( ( f ) => f.toLowerCase() );
	const has = ( re: RegExp ): boolean => lower.some( ( f ) => re.test( f ) );
	const h = html.toLowerCase();

	const hasIndex = has( /(^|\/)index\.html?$/ );
	const hasPackage = has( /(^|\/)package\.json$/ );
	if ( hasPackage && ! hasIndex ) {
		return {
			type: 'source-zip',
			label: 'Project source (not built)',
			confidence: 0.95,
			evidence: [ 'Found package.json but no built index.html' ],
			spa: true,
		};
	}
	if ( hasPackage && has( /(^|\/)src\/.*\.(tsx|jsx)$/ ) && ! has( /(^|\/)(dist|out|build)\/index\.html$/ ) ) {
		return {
			type: 'source-zip',
			label: 'Project source (not built)',
			confidence: 0.9,
			evidence: [ 'Found package.json and src/*.tsx without a dist/ build' ],
			spa: true,
		};
	}

	const rootDiv = /<div\s+id=["'](root|app)["']\s*>\s*<\/div>/.test( h );
	const viteAssets = /\/?assets\/index-[\w-]+\.(js|css)/.test( h ) || has( /(^|\/)assets\/index-[\w-]+\.js$/ );
	const next = has( /(^|\/)_next\// ) || /\/_next\/static\//.test( h );

	if ( next ) {
		evidence.push( 'Found _next/static assets' );
		if ( /v0\.dev|v0\.app|generated by v0/.test( h ) ) evidence.push( 'v0 generator hint' );
		return { type: 'next-export', label: evidence.length > 1 ? 'v0 (Next.js export)' : 'Next.js static export', confidence: 0.9, evidence, spa: true };
	}

	if ( rootDiv || viteAssets ) {
		if ( rootDiv ) evidence.push( 'Found <div id="root">' );
		if ( viteAssets ) evidence.push( 'Found /assets/index-*.js (Vite build)' );
		const lovable = /lovable|gptengineer|lovable-tagger|data-lov-/.test( h );
		const bolt = /bolt\.new|stackblitz|bolt-/.test( h );
		if ( lovable ) {
			evidence.push( 'Lovable markers in index.html' );
			return { type: 'lovable', label: 'Lovable (Vite + React)', confidence: 0.96, evidence, spa: true };
		}
		if ( bolt ) {
			evidence.push( 'Bolt/StackBlitz markers' );
			return { type: 'bolt', label: 'Bolt (Vite + React)', confidence: 0.92, evidence, spa: true };
		}
		return { type: 'vite-spa', label: 'Vite + React app', confidence: rootDiv && viteAssets ? 0.9 : 0.7, evidence, spa: true };
	}

	const htmlFiles = lower.filter( ( f ) => /\.html?$/.test( f ) );
	const tailwindCdn = /cdn\.tailwindcss\.com/.test( h );
	const inlineScripts = ( h.match( /<script(?![^>]*\bsrc=)[^>]*>/g ) ?? [] ).length;
	if ( files.length <= 1 && ( tailwindCdn || inlineScripts > 0 ) ) {
		if ( tailwindCdn ) evidence.push( 'Tailwind CDN script' );
		if ( inlineScripts ) evidence.push( `${ inlineScripts } inline script(s)` );
		if ( /claude|anthropic/.test( h ) ) evidence.push( 'Claude artifact hint' );
		if ( /gemini|canvas/.test( h ) ) evidence.push( 'Gemini Canvas hint' );
		return { type: 'ai-html', label: 'AI-generated HTML', confidence: 0.8, evidence, spa: false };
	}

	if ( htmlFiles.length > 1 || has( /(^|\/)(css|js|img|images|assets|fonts)\// ) ) {
		evidence.push( `${ htmlFiles.length } HTML file(s) with asset folders` );
		return { type: 'html-template', label: 'HTML template', confidence: 0.85, evidence, spa: false };
	}

	if ( hasIndex || htmlFiles.length === 1 ) {
		evidence.push( 'Plain HTML document' );
		return { type: 'html', label: 'HTML', confidence: 0.8, evidence, spa: false };
	}
	return { type: 'unknown', label: 'Unknown', confidence: 0.2, evidence: [ 'No HTML entry file found' ], spa: false };
}
