/**
 * Computed-style subset captured per node (FR-10).
 * Values equal to DEFAULTS are dropped to keep captures small.
 */
export const STYLE_PROPS = [
	'display',
	'position',
	'top',
	'right',
	'bottom',
	'left',
	'z-index',
	'flex-direction',
	'flex-wrap',
	'justify-content',
	'align-items',
	'align-self',
	'flex-grow',
	'flex-shrink',
	'flex-basis',
	'row-gap',
	'column-gap',
	'grid-template-columns',
	'grid-template-rows',
	'grid-column',
	'width',
	'height',
	'min-width',
	'max-width',
	'min-height',
	'box-sizing',
	'padding-top',
	'padding-right',
	'padding-bottom',
	'padding-left',
	'margin-top',
	'margin-right',
	'margin-bottom',
	'margin-left',
	'color',
	'background-color',
	'background-image',
	'background-size',
	'background-position',
	'background-repeat',
	'border-top-width',
	'border-right-width',
	'border-bottom-width',
	'border-left-width',
	'border-top-style',
	'border-top-color',
	'border-bottom-style',
	'border-bottom-color',
	'border-left-style',
	'border-left-color',
	'border-top-left-radius',
	'border-top-right-radius',
	'border-bottom-right-radius',
	'border-bottom-left-radius',
	'box-shadow',
	'opacity',
	'overflow',
	'font-family',
	'font-size',
	'font-weight',
	'font-style',
	'line-height',
	'letter-spacing',
	'text-align',
	'text-transform',
	'text-decoration-line',
	'object-fit',
	'transform',
	'filter',
	'backdrop-filter',
	'animation-name',
	'animation-duration',
	'animation-delay',
	'transition-duration',
] as const;

export type StyleProp = ( typeof STYLE_PROPS )[ number ];

/** Browser default computed values; a captured value equal to its default is omitted. */
export const DEFAULTS: Partial< Record< StyleProp, string[] > > = {
	position: [ 'static' ],
	top: [ 'auto' ],
	right: [ 'auto' ],
	bottom: [ 'auto' ],
	left: [ 'auto' ],
	'z-index': [ 'auto' ],
	'flex-wrap': [ 'nowrap' ],
	'justify-content': [ 'normal', 'flex-start', 'start' ],
	'align-items': [ 'normal', 'stretch' ],
	'align-self': [ 'auto' ],
	'flex-grow': [ '0' ],
	'flex-shrink': [ '1' ],
	'flex-basis': [ 'auto' ],
	'row-gap': [ 'normal', '0px' ],
	'column-gap': [ 'normal', '0px' ],
	'grid-template-columns': [ 'none' ],
	'grid-template-rows': [ 'none' ],
	'grid-column': [ 'auto', 'auto / auto' ],
	'min-width': [ '0px', 'auto' ],
	'max-width': [ 'none' ],
	'box-sizing': [ 'content-box' ],
	'min-height': [ '0px', 'auto' ],
	'padding-top': [ '0px' ],
	'padding-right': [ '0px' ],
	'padding-bottom': [ '0px' ],
	'padding-left': [ '0px' ],
	'margin-top': [ '0px' ],
	'margin-right': [ '0px' ],
	'margin-bottom': [ '0px' ],
	'margin-left': [ '0px' ],
	'background-color': [ 'rgba(0, 0, 0, 0)', 'transparent' ],
	'background-image': [ 'none' ],
	'background-size': [ 'auto', 'auto auto' ],
	'background-position': [ '0% 0%' ],
	'background-repeat': [ 'repeat' ],
	'border-top-width': [ '0px' ],
	'border-right-width': [ '0px' ],
	'border-bottom-width': [ '0px' ],
	'border-left-width': [ '0px' ],
	'border-top-style': [ 'none' ],
	'border-bottom-style': [ 'none' ],
	'border-left-style': [ 'none' ],
	'border-top-left-radius': [ '0px' ],
	'border-top-right-radius': [ '0px' ],
	'border-bottom-right-radius': [ '0px' ],
	'border-bottom-left-radius': [ '0px' ],
	'box-shadow': [ 'none' ],
	opacity: [ '1' ],
	overflow: [ 'visible' ],
	'font-style': [ 'normal' ],
	'letter-spacing': [ 'normal', '0px' ],
	'text-align': [ 'start', 'left' ],
	'text-transform': [ 'none' ],
	'text-decoration-line': [ 'none' ],
	'object-fit': [ 'fill' ],
	transform: [ 'none' ],
	filter: [ 'none' ],
	'backdrop-filter': [ 'none' ],
	'animation-name': [ 'none' ],
	'animation-duration': [ '0s' ],
	'animation-delay': [ '0s' ],
	'transition-duration': [ '0s' ],
};

export function isDefault( prop: string, value: string ): boolean {
	const d = DEFAULTS[ prop as StyleProp ];
	return !! d && d.includes( value );
}

/** Typography props inherited by synthetic text nodes. */
export const TEXT_PROPS = [
	'color',
	'font-family',
	'font-size',
	'font-weight',
	'font-style',
	'line-height',
	'letter-spacing',
	'text-align',
	'text-transform',
	'text-decoration-line',
] as const;
